/* eslint-disable @next/next/no-img-element */
import { VeltComments, VeltCommentsSidebar, VeltCommentTool, VeltCursor } from '@veltdev/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import styles from '../../styles/Home.module.css'
import Tabs from '../components/Tabs/Tabs'
import Toolbar from '../components/Toolbar/Toolbar'

const Home: NextPage = () => {

  const [selectedMenu, setSelectedMenu] = useState<any>();

  return (
    <div className={styles.container}>
      <Head>
        <title>Velt Nextjs Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VeltCursor />
      <VeltComments />
      <VeltCommentsSidebar />
      <VeltCommentTool />
      <Toolbar onMenuSelect={(menu: any) => setSelectedMenu(menu)} />
      <Tabs selectedMenu={selectedMenu} />
    </div>
  )
}

export default Home
