/* eslint-disable @next/next/no-img-element */
import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import styles from '../../styles/Home.module.css'
import Tabs from '../components/Tabs/Tabs'
import Toolbar from '../components/Toolbar/Toolbar'

const Home: NextPage = () => {

  const [selectedMenu, setSelectedMenu] = useState<any>();

  return (
    <div className={styles.container}>
      <Head>
        <title>Snippyly Nextjs Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <snippyly-cursor></snippyly-cursor>
      <snippyly-comments></snippyly-comments>
      <snippyly-comments-sidebar></snippyly-comments-sidebar>
      <snippyly-comment-tool>
        <div className='add-comment-btn'>
          <img src='https://cdn-icons-png.flaticon.com/512/727/727570.png' alt='Add comment' />
        </div>
      </snippyly-comment-tool>
      <Toolbar onMenuSelect={(menu: any) => setSelectedMenu(menu)} />
      <Tabs selectedMenu={selectedMenu} />
    </div>
  )
}

export default Home
